In [100]:
import pandas as pd
import numpy as np
from scipy import stats
import math

In [2]:
df = pd.read_csv('a.csv')  

In [4]:
df.describe()

-5.000000000000000000e+01
count               10079.000000
mean                    0.082349
std                   145.494730
min                  -250.000000
25%                  -128.000000
50%                     0.000000
75%                   128.500000
max                   250.000000

In [20]:
data = df.values

In [74]:
data.shape

(10079, 1)

In [92]:
a = np.ndarray((4) )

In [93]:
a[0] , a[1] , a[2] , a[3] = 1,2,3,4

In [95]:
a**2

array([  1.,   4.,   9.,  16.])

In [77]:
data - data.mean()

array([[ 118.91765056],
       [-203.08234944],
       [ 206.91765056],
       ..., 
       [  52.91765056],
       [  76.91765056],
       [  10.91765056]])

In [98]:
data.shape[0]

10079

In [99]:
((data - data.mean())**2).sum()

213338325.64996529

In [32]:
data.std(ddof = 0)

145.48751250968624

In [101]:
math.sqrt(((data - data.mean())**2).sum()/(data.shape[0] - 1))

145.49473040528315

In [33]:
data.std(ddof = 1)

145.49473040528315

In [54]:
np.median(data)

0.0

In [56]:
data_l = list(data).sort()

In [66]:
l = data.tolist()

In [70]:
l.sort()

In [72]:
l[41]

[-248.0]

In [26]:
moda = stats.mode(data)

In [27]:
moda

ModeResult(mode=array([[-140.]]), count=array([[35]]))

In [34]:
data.mean()

0.082349439428514734

In [49]:
data_up_zero = np.asarray(list(filter( (lambda x: x > 0) , data)))

In [55]:
np.median(data_up_zero)

63.0

In [50]:
data_up_zero

array([[ 119.],
       [ 207.],
       [ 245.],
       ..., 
       [  53.],
       [  77.],
       [  11.]])

In [51]:
data_up_zero = stats.mode(data_up_zero)

In [52]:
data_up_zero

ModeResult(mode=array([[ 91.]]), count=array([[35]]))